### ISSUE TITLE
arbitrary address mode is broken

### ISSUE THREAD

**Issue by mbstrange2** [joyliu37/BufferMapping#2]
Reading any address in the arbitrary_addr/manual_switch mode returns 1 regardless of the address passed in.

**Comment by joyliu37** [comment]
@mbstrange2  Are you still use this library to generate testcase for memory tile testing?

**Comment by mbstrange2** [comment]
@joyliu37 Yes. The functional model used in the fault unit tests for the memory core directly compares the functionality.  garnet will break if you change the virtual buffer.

**Comment by joyliu37** [comment]
Could you give me a pointer where those test is written? I am planning to bing the c++ functional model to the python virtual buffer class.

**Comment by mbstrange2** [comment]
https://github.com/StanfordAHA/garnet/blob/master/memory_core/memory_core.py#L104 and then tests/test_memory_core/test_memory_core.py
